package com.lenovo.ota.entites;

public class Test2 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test2.id
     *
     * @mbggenerated Thu Dec 06 09:53:30 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test2.title
     *
     * @mbggenerated Thu Dec 06 09:53:30 CST 2018
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test2.id
     *
     * @return the value of test2.id
     *
     * @mbggenerated Thu Dec 06 09:53:30 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test2.id
     *
     * @param id the value for test2.id
     *
     * @mbggenerated Thu Dec 06 09:53:30 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test2.title
     *
     * @return the value of test2.title
     *
     * @mbggenerated Thu Dec 06 09:53:30 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test2.title
     *
     * @param title the value for test2.title
     *
     * @mbggenerated Thu Dec 06 09:53:30 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}